<template><div><h1 id="contributing-guide" tabindex="-1"><a class="header-anchor" href="#contributing-guide" aria-hidden="true">#</a> Contributing Guide</h1>
<h2 id="overview" tabindex="-1"><a class="header-anchor" href="#overview" aria-hidden="true">#</a> Overview</h2>
<p>This repository employs a <a href="https://en.wikipedia.org/wiki/Monorepo" target="_blank" rel="noopener noreferrer">monorepo<ExternalLinkIcon/></a> setup with <a href="https://pnpm.io/workspaces" target="_blank" rel="noopener noreferrer">pnpm workspaces<ExternalLinkIcon/></a>, and hosts a number of associated but separated packages.</p>
<p>In the <code v-pre>packages</code> directory:</p>
<ul>
<li><code v-pre>bundler-vite</code>: The VuePress bundler package with vite. Use vite to <code v-pre>dev</code> and <code v-pre>build</code> VuePress app that generated by <code v-pre>@vuepress/core</code>.</li>
<li><code v-pre>bundler-webpack</code>: The VuePress bundler package with webpack. Use webpack to <code v-pre>dev</code> and <code v-pre>build</code> VuePress app that generated by <code v-pre>@vuepress/core</code>.</li>
<li><code v-pre>cli</code>: The VuePress command line interface (CLI) package. It will resolve user config file, and create VuePress app with <code v-pre>@vuepress/core</code>, then execute corresponding command.</li>
<li><code v-pre>client</code>: The VuePress client package. Provides the client entry, and exports types and composable utils that can be used in client side development.</li>
<li><code v-pre>core</code>: The VuePress core. Provides pure Node API to generate VuePress app, including page handling, plugin system and data preparation.</li>
<li><code v-pre>markdown</code>: The VuePress markdown package. Use <code v-pre>markdown-it</code> as the markdown parser and integrate some plugins to be used in VuePress.</li>
<li><code v-pre>shared</code>: Utilities that shared between node side and client side.</li>
<li><code v-pre>utils</code>: Utilities that should only be used in node side.</li>
</ul>
<p>In the <code v-pre>ecosystem</code> directory:</p>
<ul>
<li><code v-pre>plugin-${name}</code>: Official plugins.</li>
<li><code v-pre>theme-default</code>: The default theme.</li>
<li><code v-pre>vuepress</code>: A wrapper of <code v-pre>vuepress-vite</code>.</li>
<li><code v-pre>vuepress-vite</code>: A wrapper of <code v-pre>@vuepress/cli</code> + <code v-pre>@vuepress/bundler-vite</code> + <code v-pre>@vuepress/theme-default</code>. If users want to use default theme with vite, they can simply install this package.</li>
<li><code v-pre>vuepress-webpack</code>: A wrapper of <code v-pre>@vuepress/cli</code> + <code v-pre>@vuepress/bundler-webpack</code> + <code v-pre>@vuepress/theme-default</code>. If users want to use default theme with webpack, they can simply install this package.</li>
</ul>
<h2 id="development-setup" tabindex="-1"><a class="header-anchor" href="#development-setup" aria-hidden="true">#</a> Development Setup</h2>
<p>Pre-requirement:</p>
<ul>
<li><a href="http://nodejs.org" target="_blank" rel="noopener noreferrer">Node.js<ExternalLinkIcon/></a> <strong>version 18.16.0+</strong></li>
<li><a href="https://pnpm.io/" target="_blank" rel="noopener noreferrer">pnpm<ExternalLinkIcon/></a> <strong>version 8+</strong></li>
</ul>
<p>Clone the repo, and install dependencies:</p>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token function">pnpm</span> <span class="token function">install</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Build source code:</p>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token function">pnpm</span> build
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Start developing the documentation site:</p>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token function">pnpm</span> docs:dev
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Main tools that used in this project:</p>
<ul>
<li><a href="https://www.typescriptlang.org/" target="_blank" rel="noopener noreferrer">TypeScript<ExternalLinkIcon/></a> as the development language</li>
<li><a href="https://vitest.dev/" target="_blank" rel="noopener noreferrer">Vitest<ExternalLinkIcon/></a> for unit testing</li>
<li><a href="https://eslint.org/" target="_blank" rel="noopener noreferrer">ESLint<ExternalLinkIcon/></a> + <a href="https://prettier.io/" target="_blank" rel="noopener noreferrer">Prettier<ExternalLinkIcon/></a> for code linting and formatting</li>
</ul>
<h2 id="scripts" tabindex="-1"><a class="header-anchor" href="#scripts" aria-hidden="true">#</a> Scripts</h2>
<h3 id="pnpm-build" tabindex="-1"><a class="header-anchor" href="#pnpm-build" aria-hidden="true">#</a> <code v-pre>pnpm build</code></h3>
<p>The <code v-pre>build</code> script uses <code v-pre>tsc</code> and <code v-pre>tsup</code> to compile TypeScript source files to JavaScript dist files.</p>
<p>Also, it will copy necessary resources from source directory to dist directory, because some source files (e.g. <code v-pre>.vue</code>, <code v-pre>.css</code> files) would not be processed by <code v-pre>tsc</code> nor <code v-pre>tsup</code>, but should keep the same relative path in the dist directory.</p>
<p>You may need to run this script first after your clone this repository, because the dist files are ignored by <code v-pre>.gitignore</code>.</p>
<h3 id="pnpm-clean" tabindex="-1"><a class="header-anchor" href="#pnpm-clean" aria-hidden="true">#</a> <code v-pre>pnpm clean</code></h3>
<p>The <code v-pre>clean</code> script runs <code v-pre>clean</code> script in all packages, cleaning all the dist files and caches. In other words, it will remove all the files that generated by <code v-pre>build</code>, <code v-pre>copy</code> scripts.</p>
<p>It's used before you want to re-build source files from a clean / initial state.</p>
<h3 id="pnpm-docs" tabindex="-1"><a class="header-anchor" href="#pnpm-docs" aria-hidden="true">#</a> <code v-pre>pnpm docs:*</code></h3>
<h4 id="pnpm-docs-build-pnpm-docs-dev-pnpm-docs-clean" tabindex="-1"><a class="header-anchor" href="#pnpm-docs-build-pnpm-docs-dev-pnpm-docs-clean" aria-hidden="true">#</a> <code v-pre>pnpm docs:build</code>, <code v-pre>pnpm docs:dev</code>, <code v-pre>pnpm docs:clean</code></h4>
<p>The <code v-pre>docs:</code> prefix indicates that these scripts are for documentation, i.e. the <code v-pre>docs</code> directory.</p>
<p>VuePress is using itself to build its own documentation site.</p>
<p>You need to run <code v-pre>pnpm build</code> to build VuePress source files first, then run these <code v-pre>docs:</code> scripts to develop and build our documentation.</p>
<h4 id="pnpm-docs-serve" tabindex="-1"><a class="header-anchor" href="#pnpm-docs-serve" aria-hidden="true">#</a> <code v-pre>pnpm docs:serve</code></h4>
<p>Serve the documentation site locally.</p>
<p>You need to run <code v-pre>pnpm docs:build</code> first to generate the documentation dist files, and then run <code v-pre>pnpm docs:serve</code> to serve them.</p>
<h3 id="pnpm-lint" tabindex="-1"><a class="header-anchor" href="#pnpm-lint" aria-hidden="true">#</a> <code v-pre>pnpm lint</code></h3>
<p>The <code v-pre>lint</code> script uses ESLint to check all source files.</p>
<h3 id="pnpm-test" tabindex="-1"><a class="header-anchor" href="#pnpm-test" aria-hidden="true">#</a> <code v-pre>pnpm test</code></h3>
<p>The <code v-pre>test</code> script uses Vitest to run unit testings.</p>
<h2 id="documentation" tabindex="-1"><a class="header-anchor" href="#documentation" aria-hidden="true">#</a> Documentation</h2>
<p>VuePress documentation is powered by VuePress itself, which is built from the source code of this repository.</p>
<p>All the markdown source files are placed in <code v-pre>docs</code> directory. We are maintaining two translations:</p>
<ul>
<li>English (en-US) in <code v-pre>/</code> path</li>
<li>Chinese (zh-CN) in <code v-pre>/zh/</code> path</li>
</ul>
<p>We have two different deployments:</p>
<ul>
<li>Release deployment powered by <a href="https://www.netlify.com" target="_blank" rel="noopener noreferrer">Netlify<ExternalLinkIcon/></a>. This deployment is built from the latest released version, so users will not see unreleased changes. The domain name is <a href="https://v2.vuepress.vuejs.org" target="_blank" rel="noopener noreferrer">https://v2.vuepress.vuejs.org<ExternalLinkIcon/></a>.</li>
<li>Developer deployment powered by <a href="https://pages.github.com" target="_blank" rel="noopener noreferrer">GitHub Pages<ExternalLinkIcon/></a>. This deployment is built from the latest commit, so developers could preview the latest changes. The domain name is <a href="https://vuepress.github.io" target="_blank" rel="noopener noreferrer">https://vuepress.github.io<ExternalLinkIcon/></a>.</li>
</ul>
</div></template>


